[package]
name = "assignmatts"
authors = ["Matthew Brown <matthew.e.brown.17@gmail.com>"]
description = """
Matt's personal library of templates and helper functions for various undergraduate assignments.
"""
licence = "MIT"
repository = "https://github.com/matthew-e-brown/assignmatts"
version = "0.1.1"
entrypoint = "src/lib.typ"
exclude = ["./example"]
